---
functional:
  - Пользователи могут зарегистрироваться и войти на сайт с использованием своей электронной почты или через аккаунт GitHub или Discord.
  - Пользователь имеет возможность создавать игры, выбирая тематику, уровень сложности, время на игру и возможность выбора соперника.
  - Пользователь может писать код для решения задач на выбранном языке программирования и вносить изменения в него в процессе игры.
  - На сайте доступна таблица лидеров, где можно просматривать достижения других игроков.
  - В ходе игры пользователи могут общаться с противником через чат, а также сдаться или перезапустить игру.
  - Пользователи могут не только просматривать, но и создавать новые задания для игры.
non-functional:
  - Сайт должен быть оптимизирован для высокой скорости работы и удобства использования.
  - Сайт должен быть адаптирован под мобильные устройства и обеспечивать удобство в мобильном просмотре.
  - Сайт должен быть совместим с последними версиями популярных браузеров.
implicit:
  - Сайт должен обеспечивать безопасность и защиту персональных данных пользователей.
  - Пользователи должны иметь возможность изменять язык интерфейса на стартовой странице или в настройках профиля.
  - Пользователям должен быть предложен вводный курс или руководство по использованию сайта.
